name: Release
on:
  workflow_dispatch:
    inputs:
      MESSAGE:
        description: 'message for release body'

  push:
    tags:
    - '*'

env:
  MESSAGE: ${{ github.event.inputs.MESSAGE }}

jobs:
  release:
    name: Release on GitHub
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # get version from manifest.json
    - name: Get Version
      run: |
        echo "ReleaseVersion=v$(cat manifest.json | grep -oEm 1 '"version": "[0-9]{1,}.[0-9]{1,}(.[0-9]{1,})?"' | cut -d':' -f2 | sed 's/ //g; s/"//g')" >> ${GITHUB_ENV}

    - name: package files
      run: |
        zip -rq tap-translate.zip * -x README.md LICENSE

    - name: Create Release
      run: |
        gh release create ${{ env.ReleaseVersion }} -n "${{ env.MESSAGE }}" -t "${{ env.name }}" tap-translate.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        name: tap-translate-${{ env.ReleaseVersion }}
